### ISSUE TITLE
no results, high Sierra

### ISSUE THREAD

**Issue by hugh1li** [iansinnott/alfred-maestro#11]
<img width="706" alt="screen shot 2017-11-09 at 23 18 50" src="https://user-images.githubusercontent.com/6027595/32642757-7923d742-c5a4-11e7-8240-ff00c5fe377a.png">

**Comment by iansinnott** [comment]
Well, that's no good. It might be an issue with Keyboard Maestro though, in which case there's nothing this project can do. First of all, make sure you're using the latest KM (I think it's version 8). Then, if you are using the latest and you're still seeing no result try running the applescript directly to see if you get any results: https://github.com/iansinnott/alfred-maestro/blob/master/km.scpt

**Comment by maltsev** [comment]
@hugh1li the workflow has been completely rewritten. I've tested it with the latest Alfred, Keyboard Maestro, and macOS versions. Everything works great for me! 

You can install the new version by downloading and double-clicking _AlfredMaestro.alfredworkflow_ file from [the latest release page](https://github.com/iansinnott/alfred-maestro/releases/latest). Feel free to reopen this issue if the workflow won't work for you.
