### ISSUE TITLE
Open the macro in Keyboard Maestro editor

### ISSUE THREAD

**Issue by nikitavoloboev** [iansinnott/alfred-maestro#12]
It would be really awesome if you could open the macro in the KM editor for editing instead of running the macro. Perhaps do it with a modifier key users can set.

I can help add this but I am not very familiar with PHP.

**Comment by iansinnott** [comment]
Lol, yeah I feel you re: PHP. This lib is the only PHP I've written in a while. Anyway, totally agree. I haven't yet taken a look at what (if any) new functionality is available via the AppleScript API in version 8, so we can perhaps do more useful things like display the mapped keyboard shortcut in each alfred result (as you've suggested before).

I'm also interested in rewriting this lib in either python or javascript. I'm curious what you think.

I opened a new issue to try to consolidate things a bit: https://github.com/iansinnott/alfred-maestro/issues/13

**Comment by maltsev** [comment]
@mpco implemented this feature in his PR #23.

I released it in version [0.2.2](https://github.com/iansinnott/alfred-maestro/releases/tag/0.2.2).
