### ISSUE TITLE
[SUGGESTIONS] Create a (better) Fallback Search than mine

### ISSUE THREAD

**Issue by ybbond** [iansinnott/alfred-maestro#28]
## Details
I'd like to conveniently call Keyboard Maestro macro by name as default fallback. My current implementation is adding a `Fallback Search` trigger and connecting it to Script Filter like this:
![Screen Shot 2021-01-21 at 01 33 31](https://user-images.githubusercontent.com/25895873/105219131-ac571480-5b88-11eb-93f2-6699f2df0399.png)

However, I'd like to trigger the closest match when I hit the KM fallback option, if possible.

I have no experience in Go, with little experience with AppleScript. Open to discussion, and might help if I can.

**Comment by davidawad** [comment]
Can you share what you added to the fallback search ?

**Comment by ybbond** [comment]
Sorry, I don't use Alfred anymore. closing this
