### ISSUE TITLE
MacOS won't let me use this workflow

### ISSUE THREAD

**Issue by austinkocher** [iansinnott/alfred-maestro#34]
I've tried to install this several times, but the OS keeps preventing me from using it for security reasons. Any workaround? 

![screenshot000391](https://github.com/iansinnott/alfred-maestro/assets/86611876/89fa8b1c-f7d8-4af2-9649-b04230185cc3)

**Comment by iansinnott** [comment]
Try this: https://github.com/iansinnott/alfred-maestro/issues/26#issuecomment-783339047

You can also git clone and build the repo yourself, but that is more involved. The issue your seeing is the same with any unsigned app on macos—the move is usually to right click and then click "Open". It's unfortunate apple enforces this friction unless the developer pays them, but there's no way around it that I know of.

Closing b/c this looks like a duplicate of the issues people were having in the other thread.
