### ISSUE TITLE
Custom Macros Not Showing

### ISSUE THREAD

**Issue by freyherme** [iansinnott/alfred-maestro#5]
Hello,

When using your Alfred workflow, I am unable to pull up my custom macros.  Only the default macros show up.

Possible issues:
1. I am syncing my macros via a dropbox folder.
2. These macros are app-specific.  Even when I summon Alfred from within the app, the macros do not show.

Thanks for your help!

**Comment by iansinnott** [comment]
Hm, I need to figure out whether KM on your system is outputing all the macros. My script pulls them from KM and then formats them, so if KM isn't even passing them to my script that would be the problem. Try  running this in your terminal: 

```
osascript -e 'tell application id "com.stairways.keyboardmaestro.engine"' -e 'gethotkeys with asstring and getall' -e 'end tell'
```

That will simply run the `km.scpt` script that can be found in the root of this repository. Your terminal _should_ output a bunch of XML from Keyboard Maestro with all of your macros. Look at the output and see if you can spot the names of some of your custom macros. For example, I have a custom macro defined called "Insert Date: mm/dd/yy", so in the output from the above command I will see a line like this:

```xml
<string>Insert Date: mm/dd/yy</string>
```

So let me know if you get any of your custom macros output in the terminal and we can go from there.

**Comment by freyherme** [comment]
Hi Ian,

So, it finds my macros that are set to run in any application, and indeed, I can use your workflow to run macros that are set to run from any application.  I have many macros, however, that are set to run in Safari only.  I am unable to run those from the alfred workflow, and they do not appear in the xml output from terminal.

Thanks again for your help!

-- 
Franck
reyherme@gmail.com

On February 14, 2015 at 2:52:48 PM, Ian Sinnott (notifications@github.com) wrote:

Hm, I need to figure out whether KM on your system is outputing all the macros. My script pulls them from KM and then formats them, so if KM isn't even passing them to my script that would be the problem. Try running this in your terminal:

osascript -e 'tell application id "com.stairways.keyboardmaestro.engine"' -e 'gethotkeys with asstring and getall' -e 'end tell'

That will simply run the km.scpt script that can be found in the root of this repository. Your terminal should output a bunch of XML from Keyboard Maestro with all of your macros. Look at the output and see if you can spot the names of some of your custom macros. For example, I have a custom macro defined called "Insert Date: mm/dd/yy", so in the output from the above command I will see a line like this:

<string>Insert Date: mm/dd/yy</string>
So let me know if you get any of your custom macros output in the terminal and we can go from there.

**Comment by iansinnott** [comment]
What does that look like in KM? Can you screenshot it for me? (You can upload photos here by dropping them in the response box).

**Comment by freyherme** [comment]
Is this what you’re looking for?




-- 
Franck
reyherme@gmail.com

On February 15, 2015 at 1:44:04 PM, Ian Sinnott (notifications@github.com) wrote:

What does that look like in KM? Can you screenshot it for me? (You can upload photos here by dropping them in the response box).

**Comment by freyherme** [comment]
![keyboard_maestro_editor_and_microsoft_word](https://cloud.githubusercontent.com/assets/10999668/6205153/80b19aba-b519-11e4-803f-962a73b75d6a.jpg)

**Comment by freyherme** [comment]
Well, I fixed it by adding "Alfred 2" in the list of applications the macro is available in.  With Alfred 2 on the list of applications, I can use your workflow for these actions!  Problem solved.  :)

**Comment by iansinnott** [comment]
Nice! :clap: 

That's a strange bug, but good to know in case anyone else runs into this issue on the future.

**Comment by slyfogh** [comment]
Is this working in Alfred 4? Does not seem to work for me.

<img width="570" alt="Screen Shot 2019-08-29 at 8 42 02 AM" src="https://user-images.githubusercontent.com/2897699/63941159-f6da6d00-ca38-11e9-88e9-9701f6fce832.png">

**Comment by iansinnott** [comment]
@slyfogh not sure, maybe other users can weigh in. I'm still on Alfred 3

**Comment by nikitavoloboev** [comment]
It does work for me perfectly. 

![2019-08-30 at 09 20](https://user-images.githubusercontent.com/6391776/64005053-746cae80-cb07-11e9-8ba2-f8730911acda.png)

**Comment by slyfogh** [comment]
What could I be doing wrong? All permission settnigs for Alfred are enabled.

<img width="1016" alt="Screen Shot 2019-08-30 at 7 42 08 AM" src="https://user-images.githubusercontent.com/2897699/64018230-db836680-caf9-11e9-89d0-f3f481362886.png">
<img width="1042" alt="Screen Shot 2019-08-30 at 7 42 33 AM" src="https://user-images.githubusercontent.com/2897699/64018231-db836680-caf9-11e9-96b4-77388dc2f52c.png">

**Comment by slyfogh** [comment]
I figured it out. In my case the Macro group is set to appear in specific applications. For example Ulysses. Thus, for this workflow to work, I must execute the combination of Alfred workflow while Ulysses app is open and at the front.
