### ISSUE TITLE
Can't get any workflow.

### ISSUE THREAD

**Issue by politicus** [iansinnott/alfred-maestro#6]
Requirements checked. Checked the workflow I wanted to execute was enabled.
Reinstalled the latest version of the workflow. 
Tried the comment fix. http://www.alfredforum.com/topic/3447-alfred-maestro-keyboard-maestro-integration-for-alfred/?p=35176
Still no macros in the results. No error in Alfred's console.

**Comment by iansinnott** [comment]
Thanks for bringing this to my attention. I'll try to replicate. What are your version numbers for the following?

* OSX
* Alfred
* Keyboard Maestro
* PHP

**Comment by politicus** [comment]
OS X: 10.10.3 
Alfred: 2 v2.7.1
Keyboard Maestro: v6.4.8. Didn't work with v6.4.6 either.
PHP: 5.5.20 

I still get a "No results found" error. No error in Alfred console.

**Comment by iansinnott** [comment]
Boom :clap:  

There was indeed an update a to KM a while back that made this workflow much more powerful. Glad to hear it's working now
